### ISSUE TITLE
Things I wish you added

### ISSUE THREAD

**Issue by ZFM2004** [BEEmod/BEE2-items#1894]
- TWTM items
- furniture
- posters
- bottomless pits
- fire
- Portal Stories Mel Portal Device
- A Way to activate / choose what device your using / turn it off (including TWTM recorder)
- placing device anywhere on map
- A scroll thing for the inventory
- A way so gels can be in vactubes
- a way to change the turrets "skin"
- turret dropper
- TWTM style
- once again, all FURNITURE (including extended relaxation vault furniture & radio & clipboard & disc & etc.)
- bombs
- office furniture / items (useful for BTS)
- harmless goo
- custom music
- placeable plants/vines
- a way to record you voice as the announcer for a test chamber
- ALL doors (including the doors with the little handle)
- Quiet Fizzler
- Teleporter (so you could make a time machine map)
- a way to make things be able to be picked up
- Add Adhesion Gel
- add the turret maker
- fix the fact that some people cant see the cube thing that reflects HIGH ENERGY PELLETS & it looks like a error
- add the "trash"
- Add a way to make turrets only shoot at one thing (like a target)
- add PotatOS
- Finally, add a way to let players trigger dialouge

**Comment by ZombiePwner1** [comment]
@ZFM2004 Adhesion gel is not possible in the puzzlemaker due to the way people have re-made it.
Bottomless pits you can already make you just need the 3D BTS skybox selected.

**Comment by awesomedoctorx3** [comment]
Can't you remake it a different way?

**Comment by TeamSpen210** [comment]
No.

**Comment by TeamSpen210** [comment]
- TWTM items
	- TWTM compadibility requires remaking most of the items.
- furniture
	- No, it's a Test Chamber, not a house.
- posters
	- These are in corridors already, they might appear on walls though via Decorations.
- bottomless pits
	- These exist already.
- fire
	- Be more specific
- Portal Stories Mel Portal Device
	- If we get permission.
- A Way to activate / choose what device your using / turn it off (including TWTM recorder)
	- No, the device is specific to the game you're using.
- placing device anywhere on map
	- What?
- A scroll thing for the inventory
	- Can't be done.
- A way so gels can be in vactubes
	- Planned.
- a way to change the turrets "skin"
	- Why?
- turret dropper
	- Done and ready to release.
- TWTM style
- once again, all FURNITURE (including extended relaxation vault furniture & radio & clipboard & disc & etc.)
	- No.
- bombs
	- Planned.
- office furniture / items (useful for BTS)
	- No.
- harmless goo
	- Suggested before.
- custom music
	- You just need to write configs.
- placeable plants/vines
	- Decorations will do this.
- a way to record you voice as the announcer for a test chamber
	- No.
- ALL doors (including the doors with the little handle)
	- Why? That would be inconsistent.
- Quiet Fizzler
	- This is coded into the game.
- Teleporter (so you could make a time machine map)
	- No.
- a way to make things be able to be picked up
	- What things?
- Add Adhesion Gel
	- Can't be done.
- add the turret maker
	- Not useful, it might become a decoration.
- fix the fact that some people cant see the cube thing that reflects HIGH ENERGY PELLETS & it looks like a error
	- Which styles?
- add the "trash"
	- What trash?
- Add a way to make turrets only shoot at one thing (like a target)
	- Perhaps.
- add PotatOS
	- Not added for plot reasons and inconsistency.
- Finally, add a way to let players trigger dialouge
	- If someone can figure out a good way to do it.

**Comment by snorepion** [comment]
Yeah, I agree that a lot of those things wouldn't make any sense or be possible. I was actually trying to make the turret maker as a custom item for part of an item pack that I could send to you if you want. 
Office chairs and desks with computers would be really nice for BTS stuff, but it is a bit fluffy and useless.

**Comment by ZombiePwner1** [comment]
The placable vines idea I still have the packages for it I just need to redo the instances.
