### ISSUE TITLE
PRL27 Bug: Overgrown "Metal Pillars" are being displayed as a mysterious "Purple and Black" textures

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#2264]
![Image](https://user-images.githubusercontent.com/32555458/31258308-471f12e2-aa0c-11e7-964a-d8c1c2110b8e.jpg)

**Comment by LautaroL20** [comment]
Ah! The problem about the over trusses was that the material file is corrupted, the basetexture´s patch is unreadable: `"$basetexture" "models\\props_bts    russ"`

**Comment by CreepiX987** [comment]
What's with your "mysterious" thing that you add to every issue for no reason?

**Comment by TeamSpen210** [comment]
It's parsing the `\t` into a tab.

**Comment by Fazbear189** [comment]
I still get this error

**Comment by Fazbear189** [comment]
Why do I still get this bug? What do I do with the fix?

**Comment by LautaroL20** [comment]
@Fazbear189 - This is fixed for next release, however you can fix it yourself manually. To do this, go to: `Portal 2\bee2\materials\bee2\models\props_overgrown` then open the file: `truss_rusty.vmt` with a text editor, then replace everything that with the following and save the file: 

VertexLitGeneric
	{
	$basetexture "models/props_bts/truss"
	$surfaceprop metal
	$detail "detail/detail_rust"
	$detailscale 2
	$detailblendfactor 0.9
	$detailblendmode 0
	}

**Comment by Fazbear189** [comment]
Thank you so much!!!

**Comment by LautaroL20** [comment]
@Fazbear189 - You re welcome.

**Comment by Fazbear189** [comment]
The fix won't work anymore. I still get the missing texture no matter what I put there.

**Comment by Fazbear189** [comment]
The fix won't work anymore!
