### ISSUE TITLE
Players can still get stuck inside the "Coop Droppers"

### ISSUE THREAD

**Issue by Hottentotten** [BEEmod/BEE2-items#2518]
If you respawn at the custom "Player dropper" and move while falling down the dropper you can hit the edge of the inside of the dropper. It may stay open but once you try to jump out it will close and gets you stuck. 

![20180224192828_1](https://user-images.githubusercontent.com/33907318/36633631-45c9c7a0-1999-11e8-9b8b-3ace8013fb28.jpg)

**Comment by LautaroL20** [comment]
I thought the problem were fixed tho...

**Comment by Cellolide** [comment]
It is fixed if you just fall down. But do to the fact that you can move while falling it is still possible unfortunatly.

**Comment by LautaroL20** [comment]
Interesting, thanks for reporting it.

**Comment by Luke18033** [comment]
Does this still happen?

**Comment by LautaroL20** [comment]
Tested with the PRL 4.36.1 and i can confirm that this issue still persist.

**Comment by Luke18033** [comment]
Not sure why this has been so hard to fix...why can't they use the same closing logic as the droppers in the spawn room/checkpoints?

**Comment by LautaroL20** [comment]
> Why can't they use the same closing logic as the droppers in the spawn room/checkpoints?

Yeah, that seems to be the most reasonable to do in this case. Not sure why Coop Droppers should have a different closing logic...

**Comment by Luke18033** [comment]
I'm not actually sure if the logic is any different, I haven't checked. It just seems weird that this would repeatedly be a problem even though the normal spawn room/checkpoint droppers have never had the same issue.

**Comment by Luke18033** [comment]
Seems like this might be fixed actually, there seems to be a clip stopping me from moving over far enough to hit the side.

**Comment by Luke18033** [comment]
Okay I figured out what's going on here, for some reason the triggers are only considering players to be touching them if the player's origin is inside the trigger, rather than any part of their bounding box.

**Comment by Luke18033** [comment]
Okay, I'm amazed this has never been found before now...but it looks like triggers don't work right in rotated instances, it effectively treats the hitboxes of detected objects as if they have the same rotation.

**Comment by Luke18033** [comment]
It's not a problem for most objects since their bounding box is centered on their origin, so when rotated it ends up close to if not exactly the same, but since players have their origin at the base of their bounding box it breaks.

**Comment by Luke18033** [comment]
Okay, I did some proper testing in a separate map and the bug isn't quite what I thought...but something is definitely still messed up with rotated triggers in instances, and that seems to be the cause of this issue.

Trigger activated despite being outside of it:
![portal2_mcHzSABHVZ](https://user-images.githubusercontent.com/19228201/132970991-f6061293-6d76-4f38-94aa-06aa57e81aba.png)

Trigger not activated despite being inside of it:
![portal2_KE5VjSMCQM](https://user-images.githubusercontent.com/19228201/132970983-69ef8669-c4d3-498e-9a4f-30da8e1874bf.png)

Neither of these issues happen with an un-rotated trigger. Could someone who knows C++ maybe check the SDK code to see if they can figure out exactly what's happening here?

**Comment by Luke18033** [comment]
Regardless of exactly what's going on, it seems like the fix in BEE would be to reorient these instances to start in a ceiling orientation, so the triggers don't need to be flipped.

**Comment by Luke18033** [comment]
I figured out what the trigger bug is. It is rotating your bounding box and using that for trigger detection like I originally thought, except your *real* bounding box also has to be touching the trigger's axis-aligned bounding box for it to activate.

For rectangular axis-aligned triggers, that means the detection area is effectively equal to the intersection of your real bounding box and rotated bounding box. That's what was going on with the single checkpoint - with the instance rotated 180 degrees vertically, the intersection of the two bboxes would just be a flat rectangle along the bottom of your player.

Things get weirder for triggers that aren't rectangular and axis-aligned, since it becomes possible for you to not be touching any part of the trigger but still have it activate. If you've ever noticed the entry door trigger activating well before you actually touch it, this is why - your rotated bounding box extends forward into the trigger, and since the trigger wraps around the sides of the door as well, your real bounding box intersects its bounding box, so it activates. That also means that this doesn't happen anymore in P1 style, since I updated the door/corridor instances to default to a wall orientation.

Not sure how well I explained this, I could make a video showing the bug in more detail if necessary. This is a really interesting bug, and I'm honestly surprised that nobody seems to have found it before now. We'll definitely want to document this on the VDC, and keep it in mind for future BEE items.
