### ISSUE TITLE
Many items will not get activated after you walked thru a trigger once (Item list in description).

### ISSUE THREAD

**Issue by prrg** [BEEmod/BEE2-items#2844]
The following items will not get activated after you walked thru a Trigger Once:

* Stairs
* Half Glass Door
* Retractable Pedestal Button
* Piston Platform
* Unstationary Scaffold 
* Unstationary Scaffold - Slot
* Unstationary Scaffold - Wall Emitter

**Comment by prrg** [comment]
*I discovered I was just using the Chamberlock wrong, so yeah I guess it IS just the item.

**Comment by LautaroL20** [comment]
When using BEE2.4 after installing a new version, old resources from past releases will not be overwritten, resulting in bugs that were fixed still being present and some things not working correctly. In order to solve this annoyance, you will have to do the following:

1 - Make sure your antivirus is not blocking the compiler´s files of Beemod that are located in the `bin` folder inside the Portal 2 game´s directory. Just add the whole `bin` folder in your antivirus exception´s list, because otherwise this can cause a ****"building error"**** issue when building your puzzle.

2 - Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

3 - Wait 1 minute while Beemod removes their resources from Portal 2.

4 - Verify the Game Cache Files. 

5 - Make sure to have downloaded and unzipped the latest Item's Packages and Application version of BEE2.4, and both must be from the same Pre-Release Version, otherwise bugs may occur. Links:

https://github.com/BEEmod/BEE2.4/releases (Application)  
https://github.com/BEEmod/BEE2-items/releases (Item's Packages)

Note that if you are running Beemod on Linux or Mac Os X, or even on 32 Bit versions of Windows, issues can occur. Beemod currently works well only on 64 Bit versions of Windows 7, 8 and 10.

6 - Click on: `File ----> Options ----> Development`, then uncheck the option: `Preserve Game Directories`.

7 - Now choose your favorite Items & Style and export your palette to the game.

8 - Make sure to save these steps in a text file in case you get similar issues in the future.

9 - Happy mapmaking!

**Comment by King0191** [comment]
@LautaroL20, I know it is not technically my place. But could you please make sure to ask if they've already done that or not? Because in the OP's description, they make a point to say:
> I've tried properly reinstalling and the issue remains in pretty much every map. Other triggers work fine.

**Comment by LautaroL20** [comment]
Triggers works pretty well for me and i am sure its the same for all collaborators. Re-installing beemod will not solve his issue at all, the only 100% effective way to fix fake bugs as for today is following carefully these steps i always share.

**Comment by King0191** [comment]
The instructions you have given are how to "properly reinstall" BEE2. Given his comment. It seems to me that he DID follow those instructions. And if he's still having these issues. It might show that for some reason. it is a legit issue, perhaps on certain computer software types. Perhaps in general.

 If it later comes to light that your instructions fixed his issue. I will willingly apologize and state that what you have said is correct. However at the current moment, I cannot. As I too am having this issue, and have **according to your instructions** "Properly Re-installed BEEMod and renewing all the files"

**Comment by LautaroL20** [comment]
The instructions are not only about to how to install Bee2 properly, but to fix "bugs" that none of the collaborators are experiencing. He NEVER mentioned something like "ive followed the steps given by Lautaro" so, he clearly seems to tried fixing the issue his own way which clearly seems not giving any positive results.

**Comment by prrg** [comment]
> 
> 
> When using BEE2.4 after installing a new version, old resources from past releases will not be overwritten, resulting in bugs that were fixed still being present and some things not working correctly. In order to solve this annoyance, you will have to do the following:
> 
> 1 - Make sure your antivirus is not blocking the compiler´s files of Beemod that are located in the `bin` folder inside the Portal 2 game´s directory. Just add the whole `bin` folder in your antivirus exception´s list, because otherwise this can cause a ****"building error"**** issue when building your puzzle.
> 
> 2 - Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.
> 
> 3 - Wait 1 minute while Beemod removes their resources from Portal 2.
> 
> 4 - Verify the Game Cache Files.
> 
> 5 - Make sure to have downloaded and unzipped the latest Item's Packages and Application version of BEE2.4, and both must be from the same Pre-Release Version, otherwise bugs may occur. Links:
> 
> https://github.com/BEEmod/BEE2.4/releases (Application)
> https://github.com/BEEmod/BEE2-items/releases (Item's Packages)
> 
> Note that if you are running Beemod on Linux or Mac Os X, or even on 32 Bit versions of Windows, issues can occur. Beemod currently works well only on 64 Bit versions of Windows 7, 8 and 10.
> 
> 6 - Click on: `File ----> Options ----> Development`, then uncheck the option: `Preserve Game Directories`.
> 
> 7 - Now choose your favorite Items & Style and export your palette to the game.
> 
> 8 - Make sure to save these steps in a text file in case you get similar issues in the future.
> 
> 9 - Happy mapmaking!

I have already done this. Multiple times in fact. Once using an zip file of BEE already on my hard drive and another time re-downloading it from here. Still won't work. At this point I'm pondering re-installing Portal 2 even though Steam says my files are fine.

**Comment by LautaroL20** [comment]
Linking two triggers of the same type also works pretty well when connected to any item, i already tested this too. If @HugoBDesigner confirms i am worng, i promise i ask you pardon and ill-automatically re-open the issue.

**Comment by LautaroL20** [comment]
@TeamSpen210 - Good luck at fixing a bug that doesn't really exist.

**Comment by Dantido** [comment]
What's that?

> The only work around is to use "Volumetric Trigger Once" method

What's that?

**Comment by Overwatch-C-17** [comment]
By connecting Trigger Once block to another Trigger Once block. Then drag it somewhere to create a Large Trigger Radius. You can even make it small radius tho.

**Comment by Dantido** [comment]
> By connecting Trigger Once block to another Trigger Once block. Then drag it somewhere to create a Large Trigger Radius. You can even make it small radius tho.

It doesn't work for me....also!
This is what I did.
I made 2 trigger once and 1 stairs to the map, all connected to each other. The trigger once is in front of the other trigger block, with 1 block of distance. I walk on them, and the antline gets orange, but the stairs don't activate!

**Comment by Dantido** [comment]
And now I tried the same thing with the triggers on the same place, but NOTHING.

**Comment by Overwatch-C-17** [comment]
Whoa strange. It was work for me when I was tested it, before I remove it from my palette because of this bug.

Have you try to make the trigger radius a bit wide? just ensuring

**Comment by Dantido** [comment]
Alright. I got news. 
It seems that the trigger works with angled panels, but doesn't work with droppers or stairs.
However, I need them to work on them. 
And no, I didn't try to do that. Let me try it now...

**Comment by Dantido** [comment]
Nope, still doesn't work.

**Comment by Overwatch-C-17** [comment]
Gotta wait for the next release. I'm also not using Trigger items until this bug get fixed

**Comment by Overwatch-C-17** [comment]
**Trigger Once [Single Block]** not work on following items:
- Stairs 
- Coop Glass Door
- Piston Platform
- Pedestal Button (Retractable)
- Unstationary Scaffold
Those are the items I found so far not activated by the trigger block

**Comment by LautaroL20** [comment]
@Overwatch-C-17 - Indeed, i confirm that what you said is correct. I will open a post mentioning those specific issues with the Trigger Once.

**Comment by LautaroL20** [comment]
Well, ill gonna use the current one in order to not making a duplicate. Image:
![Trigger Once does not work with those items:](https://user-images.githubusercontent.com/12244376/48444834-d70cdd80-e773-11e8-8b8b-1cb583752539.jpg)

**Comment by Overwatch-C-17** [comment]
Probably there are still more items, i'm not check'em yet. Those are items in my palette

**Comment by Overwatch-C-17** [comment]
Sure thing.

**Comment by Overwatch-C-17** [comment]
NEW:
* Unstationary Scaffold - Slot
* Unstationary Scaffold - Wall Emitter

**Comment by LautaroL20** [comment]
Added to the description. As for now, we´ve detected that the following items will not get activated after you walked thru a trigger once:

* Stairs
* Half Glass Door
* Retractable Pedestal Button
* Piston Platform
* Unstationary Scaffold 
* Unstationary Scaffold - Slot
* Unstationary Scaffold - Wall Emitter

**Comment by TeamSpen210** [comment]
That is interesting, since all of those use the "old" input system. Must have done something wrong there. No need to test lots of other items.

**Comment by Overwatch-C-17** [comment]
Still exist in [4.32.0]

**Comment by LautaroL20** [comment]
Yep.
